config/routes.rb
TimeCard::Application.routes.draw do

  resources :users do
    resources :time_entries, except: [:new,] 
  end

  root to: "users#index"
put "/users/:user_id/time_entries/:id/upd_acc" => "time_entries#upd_acc"
end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  attr_accessible :user_id, :accomplishments, :date, :remarks, :time_in, :time_out

  belongs_to :user 

  def time_in
    value = read_attribute(:time_in)
    value.strftime("%I:%M %p") if value.present?
  end

  def time_out
    value = read_attribute(:time_out)
    value.strftime("%I:%M %p") if value.present?
  end
  
  def timed
    value = Time.now
    value.strftime("%I:%M %p") if value.present?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :company, :course, :ended_at, :first_name, :last_name, :middle_name, :started_at, :year

  has_many :time_entries

  def started_at
    value = read_attribute(:started_at)
    value.strftime("%-d/%-m/%y") unless value.blank?
  end

  def ended_at
    value = read_attribute(:ended_at)
    value.strftime("%-d/%-m/%y") unless value.blank?
  end

  def time_entry_for_today
    time_entries.where(date: Date.today).last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController

  before_filter :find_user

  def index
    @time_entries = @user.time_entries.all
  end

  def show
    @time_entry = @user.time_entries.find(params[:id])
  end


  def create
    t = @user.time_entries.new()
    t.date = Date.today
    t.time_in = Time.now
    t.date = Date.today
    t.save

    flash[:notice] = "You successfully timed in"
    redirect_to users_path
  end

 def edit
     @time_entry = @user.time_entries.find(params[:id])
  end
  def upd_acc
    @time_entry = @user.time_entries.find params[:id]
    @time_entry.update_attributes(accomplishments: params[:accomplishments]  )
    redirect_to users_path
  end
  def update
    @time_entry = @user.time_entries.find params[:id]
    @time_entry.update_attributes(time_out: Time.now)

    flash[:notice]="records updated"
    redirect_to users_path
  end

  def destroy
    time_entry = @user.time_entries.find(params[:id])
    time_entry.destroy

    redirect_to user_time_entries_path(@user)
  end





  private

    def find_user
      @user = User.find(params[:user_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def create
    u = User.new(params[:user])
    u.save

    flash[:notice] = "Record Created"
    redirect_to users_path
  end

  def update
    #search yung time entry for today
    #lagyan ng timeout using current time
    #
    @user = User.find(params[:id])

    @user.update_attributes(params[:user])
    flash[:notice] = "Record Updated"
    redirect_to users_path
  end

  def destroy
    user = User.find(params[:id])
    user.destroy

    flash[:notice] = "Record Deleted"
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
%html
  %head
    = stylesheet_link_tag "application" , :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags
    %title 
      TimeCard
      
  %body.a
    .container
      .row
        = yield
            

app/views/time_entries/_form.html.erb
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Warning!</strong> Check your information correctly.
  </div>

<%= form_for [@user,@time_entry], html: { class: "form-horizontal"} do |f|%>
  <div class="control-group">
    <%= f.label :date, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :date %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :time_in, class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :time_in, placeholder: "time_in" %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :time_out, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :time_out, placeholder: "time_out" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :accomplishments, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :accomplishments, placeholder: "accomplishments" %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :remarks, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :remarks, placeholder: "remarks" %>
    </div>
  </div>


  <br>    <%= f.submit %>
<%end%>

app/views/time_entries/_form.html.haml
.alert
  %button type="button" class="close" data-dismiss="alert">&times;</button>
  %strong Warning! Check your information correctly.


= form_for [@user,@time_entry], html: { class: "form-horizontal"} do |f|
  .control-group
    = f.label :date, class: "control-label" 
    .controls
      = f.text_field :date 

  .control-group
    = f.label :time_in, class: "control-label"  
    .controls
      = f.text_field :time_in, placeholder: "time_in" 
  
  .control-group
    = f.label :time_out, class: "control-label" 
  .controls
      = f.text_field :time_out, placeholder: "time_out" 
  
  .control-group
    = f.label :accomplishments, class: "control-label" 
    .controls
      = f.text_field :accomplishments, placeholder: "accomplishments"
  
  .control-group
  = f.label :remarks, class: "control-label" 
    .controls
      = f.text_field :remarks, placeholder: "remarks" 
    
  %br    = f.submit 

app/views/time_entries/edit.html.haml
%h1 Edit Time Entries

  = render "form" 

app/views/time_entries/index.html.erb
<div class="well well-small">
  <h1>
    Time Entry
  </h1> 
</div>

<form class="form-search">
  <input type="text" class="input-medium search-query">
  <button type="submit" class="btn">Search</button>
</form>

  <% if flash[:notice] %>
<div class="well well-large">
    <div class="alert alert-info">
      <b>Notice:</b><%=flash[:notice] %>
    </div>
</div>
  <% end %>

<ul class="thumbnails">
  <% @time_entries.each do |time_entry| %>
    <li class="span4">
    <div class="thumbnail">
      <img data-src="http://placehold.it/300x200">
      <h6><%= time_entry.date %></h4>
      <h4><%= time_entry.time_in %></h4>
      <h4><%= time_entry.time_out %></h4>
      <h4><%= time_entry.accomplishments %></h4>
      <h4><%= time_entry.remarks %></h4>
      <%= link_to "Show", user_time_entry_path(params[:user_id],time_entry.id), class: "btn btn-warning" %>
    </div>
    </li>
  <% end %>
</ul>

app/views/time_entries/index.html.haml
.well.well-large
  %h1 Time Entry

  %form.form-search
    %input.input-medium.search-query{ type: "text" }
    %button.btn{ type:"submit" } Search

.well.well-large
  - if flash[:notice] 
    .alert.alert-info
    %b Notice:
    = flash[:notice]    

  %ul.thumbnails
    - @time_entries.each do |time_entry|
      %li.span4
        %h6= time_entry.date
        %h4= time_entry.time_in
        %h4= time_entry.time_out
        %h4= time_entry.accomplishments
        %h4= time_entry.remarks
        %table
          %tr
            %td
              = link_to "Show", user_time_entry_path(params[:user_id],time_entry.id), class: "btn btn-warning"
            %td
              = link_to "Edit Accomplishment", edit_user_time_entry_path, class: "btn"

app/views/time_entries/new.html.erb
<h1>
  Time Entries
</h1>

<%= render "form" %>

app/views/time_entries/new.html.haml
<h1>
  Time Entries
</h1>

<%= render "form" %>

app/views/time_entries/show.html.haml
%h1 Time entry show
%table
  %tr
    %td
      date
      = @time_entry.date
  %tr
    %td
      time_in
      = @time_entry.time_in
  %tr
    %td
      time_out
      = @time_entry.time_out
  %tr
    %td
      accomplishments
      = @time_entry.accomplishments
  %tr
    %td
      remarks
      = @time_entry.remarks

= link_to "Click here to delete this time_entry", "/users/#{params[:user_id]}/time_entries/#{params[:id]}", method: :delete 

app/views/users/_form.html.haml
= form_for @user do |user|
  .control-group
    %label.control-label
      First Name:
    .controls
      = user.text_field :first_name , placeholder: "First Name" 
      
  .control-group
    %label.control-label
      Middle Name:
    .controls
      = user.text_field :middle_name , placeholder: "Middle Name"

  .control-group
    %label.control-label
      Last Name:
    .controls
      = user.text_field :last_name , placeholder: "Last Name" 

  .control-group
    %label.control-label
      Course:
    .controls
      = user.text_field :course , placeholder: "Course"

  .control-group
    %label.control-label
      Year:
    .controls
      = user.text_field :year , placeholder: "Year"

  .control-group
    %label.control-label
      Company:
    .controls
      = user.text_field :company , placeholder: "Company" 
    
  .control-group
    %label.control-label
      Started At:
    .controls
      = user.text_field :started_at , placeholder: "Started At"
    
  .control-group
    %label.control-label
      Ended At:
    .controls
      = user.text_field :ended_at , placeholder: "Ended At"  
  = user.submit class:"btn btn-primary"

app/views/users/edit.html.haml
.well.well-large
  %h1 Edit User

= link_to "Home" , users_path , method: "get" ,class: "btn btn-primary"
%br
%br
.well.well-large
  = form_tag "/users/#{@user.id}", method:"put", class: "form-horizontal" do 
    = render "form" 

app/views/users/index.html.haml
%br
  .well.well-large
    %h1
      User List
  .well.well-large
    - if flash[:notice]
      .alert.alert-sucess 
        %b Notice: 
        = flash[:notice]  
    = link_to "Register!", new_user_path , method: "get" , class: "btn btn-primary"
    %br
    %br
    %table.table.table-striped
      %tr
        %th
          Name:
        %th
          Course/Year
        %th
          Company:
        %th
          Stay Duration:
        %th
          Action:
        %th
          Time:
      -@users.each do |user|
      %tr
        %td
          = user.last_name
          ,
          = user.first_name 
          = user.middle_name 
        %td
          =user.course 
          -
          =user.year
        %td
          =user.company
        %td
          From:
          = user.started_at 
          %br
          To:
          = user.ended_at
        %td
          .btn-group
            %a{:class => "btn btn-primary dropdown-toggle" ,"data-toggle" => "dropdown" }
              Action
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "Show", "/users/#{user.id}" , method: "get"
              %li
                = link_to "Edit", "/users/#{user.id}/edit" , method:"get"
              %li
                = link_to "Delete", "/users/#{user.id}", method: "delete", confirm: "Are you sure you want to delete this user?" 
              %li.divider
              %li
                = link_to "View Time Entries", "/users/#{user.id}/time_entries" , method: :get 
        %td
          - teft = user.time_entry_for_today  
            - if teft.blank? or (teft.present? && teft.time_in.blank?) 
              = link_to "Time In", "/users/#{user.id}/time_entries" , method: :post , class: "btn"
            - elsif teft.time_in.present? && teft.time_out.blank? 
              = link_to "Time Out", "/users/#{user.id}/time_entries/#{teft.id}" , method: :put , class: "btn"
            - else
              You have already timed out.

app/views/users/new.html.haml
.well.well-small
  %h1 Registration

= link_to "Home" , users_path , method: "get" ,class: "btn btn-primary"
%br
%br
.well.well-small
  = form_tag "/users", method:"post", class: "form-horizontal" do 
    = render "form" 

app/views/users/show.html.haml
%h1
  Show User
%table
  %tr
    %th
      First Name:
    %td
      = @user.first_name
  %tr
    %th
      Middle Name:
    %td
      = @user.middle_name
  %tr
    %th
      Last Name:
    %td
      = @user.last_name
  %tr
    %th
      Course:
    %td
      = @user.course
  %tr
    %th
      Year:
    %td
      = @user.year
  %tr
    %th 
      Company
    %td
      = @user.company
  %tr
    %th
      Started At:
    %td
      = @user.started_at
  %tr
    %th
      Ended At:
    %td
      = @user.ended_at
= link_to "Click here to delete this user", "/users/#{@user.id}", method: :delete
%br
= link_to "Home" , "/users" ,class: "btn" 